### ISSUE TITLE
Index Job need ability to allow developers to determine descendants

### ISSUE THREAD

**Issue by MiracleManS** [TCB-Internet-Solutions/vulcan#5]
When working with Indexing, custom content providers can cause extremely slow indexing.

The ability to declare how descendants are selected makes this an easier problem to solve (vs having to write your own Indexing service).

**Comment by dan-matthews** [comment]
You can always control what gets indexed using the control-content-indexing feature (see http://world.episerver.com/blogs/Dan-Matthews/Dates/2017/1/vulcan-comes-of-age/). You could use this to exclude items in an external content provider.

Of course, you may want to control the indexing of a custom content provider in terms of how descendents are generated etc. rather than just exclude, in which case this won't help you much.

**Comment by bmcdavid** [comment]
Content indexing via scheduled job can now be controlled by an implementation of IVulcanSearchContentLoader.GetSearchContentReferences(IVulcanContentIndexer contentIndexer), the default implementation works as prior versions.
